# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: baaec2fb2ed21ef693231090e3774f9c251a7d4dda895a5baeda268838dfd849221727be63dcf73cd74e10b4da876b9c4f2801faf4d7d52e30524598e752786d

test:
  secret_key_base: d9653dbfa4d774f3249639c40ea0081926ee10646f4d4ba24f6a435d0b9ae3368c88d19a3433f919abb77aff358bf97a0cc205989831dc54b5f7011d965bed1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
